services:
    Welp\IcalBundle\Factory\Factory: '@welp_ical.factory'
    welp_ical.factory:
        class: Welp\IcalBundle\Factory\Factory
        calls:
            - [ setTimezone, ['%welp_ical.default_timezone%']]
            - [ setProdid, ['%welp_ical.default_prodid%']]
